### ISSUE TITLE
shell hangs when `echo` is used

### ISSUE THREAD

**Issue by hacker-DOM** [tusharsadhwani/zxpy#38]
So for the following script
```python3
#! /usr/bin/env zxpy

~'echo Hello'
```
once I executed it, the shell hangs after printing Hello. When I press ctrl+c, I get:
```
^CTraceback (most recent call last):
  File "/usr/local/bin/zxpy", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/zx.py", line 59, in cli
    run_zxpy(filename, module)
  File "/usr/local/lib/python3.7/site-packages/zx.py", line 136, in run_zxpy
    "$shlex_quote": shlex.quote,
  File "./bug.py", line 3, in <module>
    ~'echo Hello'
  File "/usr/local/lib/python3.7/site-packages/zx.py", line 100, in run_shell_print
    sys.stdout.buffer.write(text)
KeyboardInterrupt
```

**Comment by tusharsadhwani** [comment]
I'm unable to reproduce it :/ This is very weird.

Can you tell a few more things?

- What operating system are you on?
- Can you run `pip install -U zxpy` and confirm you're on v1.5.0?
- Does it reproduce in the zxpy shell as well? like so:
  ```pycon
  $ zxpy              
  zxpy shell
  Python 3.10.0b3 (default, Jun 19 2021, 19:24:06) [GCC 9.3.0]

  >>> ~'echo Hello'
  Hello
  >>>
  ```

**Comment by hacker-DOM** [comment]
> os
macOS 11.6

> version
1.5.0

> shell
yes, also occurs in the shell. fwiw, when I do `python3 --version` I get 3.9.1, but when I do `zxpy` I get 

```
zxpy shell
Python 3.9.7 (default, Oct 13 2021, 06:45:31)
[Clang 13.0.0 (clang-1300.0.29.3)]

>>>
```

> PYTHONUNBUFFERED=1 zxpy myfile.py
same thing

I'll also try on my secondary machine

**Comment by hacker-DOM** [comment]
It seems to work. However, in the shell the behavior is still buggy

**Comment by tusharsadhwani** [comment]
I'm guessing you updated it on one python version but not the other?

Anyway, glad that it's fixed now.
