### ISSUE TITLE
Crash if shell return empty result (py3.10)

### ISSUE THREAD

**Issue by scailer** [tusharsadhwani/zxpy#41]
```
$ zxpy
zxpy shell
Python 3.10.1 (main, Dec 11 2021, 17:22:55) [GCC 11.1.0]

>>> a = ~'ls'  # many lines here
>>> len(a)
642
>>> b = ~'ls | grep q'  # zero lines here (empty output)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/zx.py", line 324, in install
    exec(code_obj)
  File "<input>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/zx.py", line 83, in run_shell
    with create_shell_process(command) as stdout:
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/lib/python3.10/site-packages/zx.py", line 78, in create_shell_process
    raise ChildProcessError(process.returncode)
ChildProcessError: 1
```

**Comment by tusharsadhwani** [comment]
Thanks for the report! I'll fix this within today.

Let me know if I forget lol.

**Comment by tusharsadhwani** [comment]
That's just how grep works.
```console
tushar@pop-os:~$ ls | grep a
arduino
Downloads
Templates
tushar@pop-os:~$ echo $?
0
tushar@pop-os:~$ ls | grep q
tushar@pop-os:~$ echo $?
1
```
Not having a script crash when a command returns an error would be a bad idea. For that reason this is how it behaves. It's similar to `set -e` in bash.

To not get this error, you can do this:
```python
stdout, stderr, returncode = ~'ls | grep q'
# Now you can check if the return code was 0 or not
...
```
