### ISSUE TITLE
unary operator syntax doesn't work with print()

### ISSUE THREAD

**Issue by jack1142** [tusharsadhwani/zxpy#7]
Code:
```py
#! /usr/bin/env zxpy

var = "test string"

print(~f"echo {var}")
```
Output:
```
$ ./simplescript.py
Traceback (most recent call last):
  File "/home/ubuntu/zxpy-test/venv/bin/zxpy", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/zxpy-test/venv/lib/python3.8/site-packages/zx.py", line 55, in cli
    run_zxpy(filename, module)
  File "/home/ubuntu/zxpy-test/venv/lib/python3.8/site-packages/zx.py", line 85, in run_zxpy
    exec(compile(module, filename, mode='exec'))
  File "./simplescript.py", line 5, in <module>
    print(~f"echo {var}")
TypeError: bad operand type for unary ~: 'str'
```

zxpy version: 1.2.3

**Comment by tusharsadhwani** [comment]
Yeah, I was suspecting this while patching the last issue. BRB

**Comment by tusharsadhwani** [comment]
Hi, can you test it with zxpy version 1.2.4?

**Comment by jack1142** [comment]
Works!
![image](https://user-images.githubusercontent.com/6032823/119177342-7cebe200-ba6c-11eb-9636-8ce6d812dd31.png)
