### ISSUE TITLE
Improve zx REPL

### ISSUE THREAD

**Issue by tusharsadhwani** [tusharsadhwani/zxpy#9]
- Has some weird variable scoping issues (eg. recursive functions don't work)
- Autocomplete barely works (can probably be fixed by reading and appending to the `~/.python_history` file)

**Comment by tusharsadhwani** [comment]
```python
>>> def f(n):
...   if n < 2:
...     return 1
...   return f(n-1) + f(n-2)
...
>>> f(10)
Traceback (most recent call last):
  File "/home/tushar/.local/lib/python3.8/site-packages/zx.py", line 325, in install
    exec(code_obj)
  File "<input>", line 1, in <module>
  File "<input>", line 4, in f
NameError: name 'f' is not defined
```

**Comment by tusharsadhwani** [comment]
While you're at it, also try and swap out the procedural logic for `compile_command` with the `codeop.CommandCompiler` class: https://docs.python.org/3.11/library/codeop.html#codeop.CommandCompiler
